### ISSUE TITLE
CORS issues not solve for chrome

### ISSUE THREAD

**Issue by shushengfuqin** [atomata/capstone_WebClient#24]
The cors issue is solved in azure platform. 
Use firefox web browser, the application is working fine
<img width="1421" alt="Screen Shot 2021-11-21 at 14 22 31" src="https://user-images.githubusercontent.com/35609373/142776161-7c72caba-563d-4550-babd-d8e40f976e7b.png">
<img width="1366" alt="Screen Shot 2021-11-21 at 14 21 20" src="https://user-images.githubusercontent.com/35609373/142776163-2ffdbd1e-8e50-4f34-ae37-7e51ec954b0a.png">

However while using Chrome, the CORS issue still exist. 
<img width="720" alt="Screen Shot 2021-11-21 at 14 23 45" src="https://user-images.githubusercontent.com/35609373/142776175-7fa13716-a411-405d-b51b-0024e23b109e.png">
<img width="673" alt="Screen Shot 2021-11-21 at 14 23 30" src="https://user-images.githubusercontent.com/35609373/142776176-589c5a9e-6ec0-4815-9822-dfd647b21214.png">

Fyi: I disabled corsE in firefox. Thus in therory, if cors issue haven't been solved, firefox should not be capable to function. I also cleaned the cache and history with firefox to double check.

**Comment by mckenzietsean** [comment]
Website loads as intended on both Firefox and Chrome. Will await for others to give their inputs.

**Comment by shushengfuqin** [comment]
> Website loads as intended on both Firefox and Chrome. Will await for others to give their inputs.

So maybe it's because of chrome's cache?
I'll try to clean the cache from chrome and try again

**Comment by shushengfuqin** [comment]
It's working fine after hard clean cache and refresh
<img width="1429" alt="Screen Shot 2021-11-21 at 14 44 28" src="https://user-images.githubusercontent.com/35609373/142776635-3e082989-3df7-416a-9574-cb203905030e.png">
