### ISSUE TITLE
3 Bugs according to sonarqube

### ISSUE THREAD

**Issue by shushengfuqin** [atomata/capstone_WebClient#29]
In the file pages/app.global.css
in line 66,67,68
sonarqube is reporting a bug
<img width="850" alt="Screen Shot 2021-11-25 at 10 43 45" src="https://user-images.githubusercontent.com/35609373/143470656-3aabc2bc-04bc-4efb-bdde-05bfc3d07e67.png">

I am not sure how important this is. Please take a look so we can either fix this or simply tell sonarqube to ignore it because of any reason.

**Comment by mckenzietsean** [comment]
Fixed in PR #52.
